### ISSUE TITLE
Chicken behavior changed

### ISSUE THREAD

**Issue by Ryuushen** [Siphalor/spiceoffabric#61] opened 2022-10-01 10:32 UTC
Once this mod installed, Chicken won't follow Wheat Seeds nor eat Wheat Seeds and breed anymore.

Fabric 1.18.2

**Comment by Siphalor** [comment] 2022-10-02 00:25
Thanks for reporting the issue.

I am not able to reproduce the issue though. Therefore, can you please provide the following information:

- The complete game log
- How did you come to the conclusion that this mod is causing the issue?
- Can you reproduce this in a fresh world or do you need to do anything special?

**Comment by Ryuushen** [comment] 2022-10-02 18:53
That’s interesting. I’m actually making a modpack and using this in it. The reason i come to conclusion is that when i uninstall this mod, the chicken follows me when im holding wheat seeds and when i install it they stopped. Possibly conflict with other mods. Would it be okay if i send you my curseforge export profile of my modpack?

**Comment by Siphalor** [comment] 2022-10-02 19:13
The way you describe it, it may well be a mod compatibility issue.
Especially if the modpack is big, I‌ probably won't have the time to test this through.

To pin such issues down, you can go by disabling removing half of the mods and trying to reproduce the issue.
By repeating this a few times, you can quickly pin down which other mod may be causing the issue, since you can always rule out half of the mods.
If it's just a two mod incompatibility, you should be able to identify it in a reasonable time.
If it's a three mod incompatibility, it gets a lot more annoying, but let's just hope that that's not the case.

Anyway, it makes sense to upload the game log, so the whole mod list with libraries, logs and everything relevant is here for reference.

**Comment by Ryuushen** [comment] 2022-10-02 20:02
So after couple of test, definitely mod conflict. I will test it out a bit more and try to pin down what mod. But here is the 2 game logs i tried, with and without, same world. Thank you for helping, I like this mod a lot

Without Spice of Fabric
[Chicken Works.log](https://github.com/Siphalor/spiceoffabric/files/9693380/Chicken.Works.log)

With Spice of Fabric
[Chicken Not Working.log](https://github.com/Siphalor/spiceoffabric/files/9693379/Chicken.Not.Working.log)

**Comment by Ryuushen** [comment] 2022-10-02 20:20
I found the reason, it conflicts with "Croptopia"

**Comment by Siphalor** [comment] 2022-10-02 23:22
Ah, thanks for the work :)

I have identified the issue in Croptopia and plan to submit a patch.

I fear though that they don't update their 1.18 version anymore, so you probably won't get an official fix for this.

To give a bit of insight: The incompatibility is actually between Nbt Crafting (dependency of Spice of Fabric) and Croptopia.
Croptopia has a small bit of code that doesn't use the ideal function for a thing, which just goes unnoticed in Vanilla.

When I submit the patch, I'm gonna ask for a 1.18 fix, so let's see how they react :)

**Comment by Ryuushen** [comment] 2022-10-02 23:35
Thank YOU! 

Also another thing is you can apparently feed chicken with Croptopia Seeds

**Comment by Siphalor** [comment] 2022-10-02 23:48
Yep, that's basically where the issue is ^^

Also, I just noticed that the 1.18 version is supported, it is in fact the master branch, so the patching shouldn't be a problem :)

**Comment by Siphalor** [comment] 2022-10-03 00:28
Patch is merged in Croptopia :+1:

**Closed as completed by Siphalor** 2022-10-03 00:28 UTC
Labels: bug

**Comment by Ryuushen** [comment] 2022-10-03 00:34
Perfect. Thank you very much for following through. Have a good weekend :)
