### ISSUE TITLE
Food history config not editable

### ISSUE THREAD

**Issue by rinandstyx** [Siphalor/spiceoffabric#77] opened 2023-01-18 23:56 UTC
I can change the food history to shorten, but despite this it still tracks food past then and slows down the eating of them

**Comment by rinandstyx** [comment] 2023-01-18 23:58
version i was on is [1.19.2] 1.6.0-beta.2

**Comment by Siphalor** [comment] 2023-02-10 11:23
Duplicate of #66

**Closed as not planned** 2023-02-10 11:24 UTC
Labels: bug
